highincome_countries = [
    'Australia',
    'New Zealand',
    'Brunei Darussalam',
    'Japan',
    'Republic of Korea',
    'Singapore',
    'Canada',
    'Greenland',
    'United States',
    'Argentina',
    'Chile',
    'Uruguay',
    'Andorra',
    'Austria',
    'Belgium',
    'Cyprus',
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Iceland',
    'Ireland',
    'Israel',
    'Italy',
    'Luxembourg',
    'Malta',
    'Monaco',
    'Netherlands',
    'Norway',
    'Portugal',
    'San Marino',
    'Spain',
    'Sweden',
    'Switzerland',
    'United Kingdom'
]