highincome_countries = [
    'Australia',
    'New Zealand',
    'Brunei Darussalam',
    'Japan',
    'Republic of Korea',
    'Singapore',
    'Canada',
    'Greenland',
    'United States',
    'Argentina',
    'Chile',
    'Uruguay',
    'Andorra',
    'Austria',
    'Belgium',
    'Cyprus',
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Iceland',
    'Ireland',
    'Israel',
    'Italy',
    'Luxembourg',
    'Malta',
    'Monaco',
    'Netherlands',
    'Norway',
    'Portugal',
    'San Marino',
    'Spain',
    'Sweden',
    'Switzerland',
    'United Kingdom'
]


country_code_to_name = {'PHL': 'Philippines',
 'HUN': 'Hungary',
 'SMR': 'San Marino',
 'TLS': 'Timor-Leste',
 'GHA': 'Ghana',
 'ZMB': 'Zambia',
 'FRA': 'France',
 'HND': 'Honduras',
 'DJI': 'Djibouti',
 'JPN': 'Japan',
 'BGD': 'Bangladesh',
 'FJI': 'Fiji',
 'LBR': 'Liberia',
 'KWT': 'Kuwait',
 'ARM': 'Armenia',
 'ISL': 'Iceland',
 'GEO': 'Georgia',
 'DOM': 'Dominican Republic',
 'IRQ': 'Iraq',
 'GBR': 'United Kingdom',
 'SLV': 'El Salvador',
 'LKA': 'Sri Lanka',
 'BRN': 'Brunei Darussalam',
 'KNA': 'Saint Kitts and Nevis',
 'KEN': 'Kenya',
 'SDN': 'Sudan',
 'POL': 'Poland',
 'PAN': 'Panama',
 'GNB': 'Guinea-Bissau',
 'GRC': 'Greece',
 'NPL': 'Nepal',
 'LSO': 'Lesotho',
 'FSM': 'Micronesia (Federated States of)',
 'MAR': 'Morocco',
 'MNG': 'Mongolia',
 'CHN': 'China',
 'SVK': 'Slovakia',
 'MEX': 'Mexico',
 'DNK': 'Denmark',
 'ASM': 'American Samoa',
 'DMA': 'Dominica',
 'SGP': 'Singapore',
 'HTI': 'Haiti',
 'LBN': 'Lebanon',
 'CHL': 'Chile',
 'TUV': 'Tuvalu',
 'LCA': 'Saint Lucia',
 'RUS': 'Russian Federation',
 'CHE': 'Switzerland',
 'CRI': 'Costa Rica',
 'MRT': 'Mauritania',
 'ZAF': 'South Africa',
 'SRB': 'Serbia',
 'ETH': 'Ethiopia',
 'ISR': 'Israel',
 'BRA': 'Brazil',
 'QAT': 'Qatar',
 'SWZ': 'Eswatini',
 'IRN': 'Iran (Islamic Republic of)',
 'NRU': 'Nauru',
 'MKD': 'North Macedonia',
 'LUX': 'Luxembourg',
 'SLE': 'Sierra Leone',
 'AND': 'Andorra',
 'TTO': 'Trinidad and Tobago',
 'BFA': 'Burkina Faso',
 'LAO': "Lao People's Democratic Republic",
 'NOR': 'Norway',
 'SOM': 'Somalia',
 'BGR': 'Bulgaria',
 'GRL': 'Greenland',
 'DEU': 'Germany',
 'ARG': 'Argentina',
 'CAN': 'Canada',
 'GIN': 'Guinea',
 'VCT': 'Saint Vincent and the Grenadines',
 'NZL': 'New Zealand',
 'MHL': 'Marshall Islands',
 'BHS': 'Bahamas',
 'PLW': 'Palau',
 'CYP': 'Cyprus',
 'GUY': 'Guyana',
 'STP': 'Sao Tome and Principe',
 'TKM': 'Turkmenistan',
 'ECU': 'Ecuador',
 'TCD': 'Chad',
 'BDI': 'Burundi',
 'KAZ': 'Kazakhstan',
 'ROU': 'Romania',
 'TKL': 'Tokelau',
 'UGA': 'Uganda',
 'SWE': 'Sweden',
 'MDA': 'Republic of Moldova',
 'GMB': 'Gambia',
 'GRD': 'Grenada',
 'CZE': 'Czechia',
 'CUB': 'Cuba',
 'MMR': 'Myanmar',
 'NAM': 'Namibia',
 'COL': 'Colombia',
 'MLT': 'Malta',
 'GTM': 'Guatemala',
 'PRK': "Democratic People's Republic of Korea",
 'WSM': 'Samoa',
 'ALB': 'Albania',
 'KOR': 'Republic of Korea',
 'TGO': 'Togo',
 'MWI': 'Malawi',
 'VNM': 'Viet Nam',
 'CMR': 'Cameroon',
 'CAF': 'Central African Republic',
 'AUT': 'Austria',
 'GAB': 'Gabon',
 'UKR': 'Ukraine',
 'BTN': 'Bhutan',
 'MLI': 'Mali',
 'LVA': 'Latvia',
 'JOR': 'Jordan',
 'SYR': 'Syrian Arab Republic',
 'IRL': 'Ireland',
 'JAM': 'Jamaica',
 'FIN': 'Finland',
 'IDN': 'Indonesia',
 'BHR': 'Bahrain',
 'VUT': 'Vanuatu',
 'HRV': 'Croatia',
 'GNQ': 'Equatorial Guinea',
 'BLZ': 'Belize',
 'MDV': 'Maldives',
 'RWA': 'Rwanda',
 'AZE': 'Azerbaijan',
 'NIC': 'Nicaragua',
 'COK': 'Cook Islands',
 'ARE': 'United Arab Emirates',
 'COM': 'Comoros',
 'PSE': 'Palestine',
 'VEN': 'Venezuela (Bolivarian Republic of)',
 'BWA': 'Botswana',
 'VIR': 'United States Virgin Islands',
 'THA': 'Thailand',
 'AFG': 'Afghanistan',
 'SVN': 'Slovenia',
 'KIR': 'Kiribati',
 'ZWE': 'Zimbabwe',
 'LBY': 'Libya',
 'BMU': 'Bermuda',
 'ERI': 'Eritrea',
 'TJK': 'Tajikistan',
 'KHM': 'Cambodia',
 'PAK': 'Pakistan',
 'AUS': 'Australia',
 'SAU': 'Saudi Arabia',
 'NGA': 'Nigeria',
 'SUR': 'Suriname',
 'EST': 'Estonia',
 'PNG': 'Papua New Guinea',
 'PRY': 'Paraguay',
 'NER': 'Niger',
 'IND': 'India',
 'TZA': 'United Republic of Tanzania',
 'GUM': 'Guam',
 'MNE': 'Montenegro',
 'KGZ': 'Kyrgyzstan',
 'SSD': 'South Sudan',
 'MDG': 'Madagascar',
 'TUR': 'Turkey',
 'TON': 'Tonga',
 'PRT': 'Portugal',
 'AGO': 'Angola',
 'MYS': 'Malaysia',
 'NIU': 'Niue',
 'CIV': "Côte d'Ivoire",
 'BRB': 'Barbados',
 'MOZ': 'Mozambique',
 'DZA': 'Algeria',
 'SEN': 'Senegal',
 'COD': 'Democratic Republic of the Congo',
 'TWN': 'Taiwan (Province of China)',
 'PRI': 'Puerto Rico',
 'ITA': 'Italy',
 'PER': 'Peru',
 'URY': 'Uruguay',
 'BOL': 'Bolivia (Plurinational State of)',
 'MUS': 'Mauritius',
 'UZB': 'Uzbekistan',
 'OMN': 'Oman',
 'MCO': 'Monaco',
 'USA': 'United States of America',
 'NLD': 'Netherlands',
 'COG': 'Congo',
 'BEN': 'Benin',
 'ATG': 'Antigua and Barbuda',
 'SYC': 'Seychelles',
 'BIH': 'Bosnia and Herzegovina',
 'SLB': 'Solomon Islands',
 'EGY': 'Egypt',
 'BLR': 'Belarus',
 'MNP': 'Northern Mariana Islands',
 'ESP': 'Spain',
 'CPV': 'Cabo Verde',
 'BEL': 'Belgium',
 'TUN': 'Tunisia',
 'LTU': 'Lithuania',
 'YEM': 'Yemen'}


country_name_to_code = {v:k for k, v in country_code_to_name.items()}